# server port ?? ??? ??
server:
  port: 8001

# driver config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

# mybatis 환경 설정 (현재 @Mapper 애노테이션 사용한 클래스는 인지한 상태.
# 추가로 MenuMapper.xml 이라는 파일의 존재를 알아야 하므로 아래와 같이 설정 추가해줌
mybatis:
  mapper-locations: mappers/**/*.xml
  # xml 파일이 어디있는 지 명시해줌
  # ** => mapper  하위의 모든 폴더를 나타냄 = 하위 디렉토리까지 포함한다는 뜻
  # * => 문자열 = 문자열을 비교하겠다는 뜻
  # 즉, 문자열.xml 에 해당하는 모든 파일들을 매퍼로서 등록하겠다는 뜻